SignalException:
  Enabled: false

RaiseArgs:
  Enabled: false

SpaceAroundBlockBraces:
  EnforcedStyle: space_inside_braces
Lambda:
  Enabled: false

GlobalVars:
  AllowedVariables:
    - $NO_FFI_SPEC

Documentation:
  Enabled: false