SignalException:
  Enabled: false

RaiseArgs:
  Enabled: false

SpaceInsideBlockBraces:
  Enabled: true
SpaceBeforeBlockBraces:
  Enabled: true

Lambda:
  Enabled: false

Documentation:
  Enabled: false