name: RSpec Matrix
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        ruby: [3.0, 3.1, 3.2, 3.3, 3.4]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: sudo apt-get install libjemalloc2 --yes
    - run: bundle install
    - run: bundle exec rake compile
    - run: bundle exec rake spec
    - run: LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2 bundle exec rake spec
